// Portfolio data — derived from profile baseline
export const PROFILE = {
  name: "Lounas Gana",
  role: "Robotics & AI Engineer",
  tagline: "Building autonomous systems where perception, planning, control & software must work together — under real constraints.",
  location: "Clermont-Ferrand, France",
  email: "lounasgana@gmail.com",
  phone: "+33 7 43 16 66 90",
  linkedin: "linkedin.com/in/lounasgana",
  status: "M2 Robotics & Artificial Perception · Université Clermont Auvergne · Graduating 2026",
  stats: [
    { v: "1/16", l: "M2 S1 Rank" },
    { v: "15.60", l: "M2 S1 Avg /20" },
    { v: "500 Hz", l: "CLF-CBF-QP loop" },
    { v: "< 6 cm", l: "Drone pos. RMSE" },
    { v: "≈ 90 %", l: "PointNet ModelNet40" },
    { v: "C2 / C2", l: "FR · EN" },
  ],
};

export const PROJECTS = [
  {
    id: "mobile-manip",
    num: "01",
    year: "2025–26",
    title: "Mobile Manipulation for Technician Assistance",
    tags: ["ROS2", "Isaac Sim", "MoveIt", "Nav2", "RGB-D", "TinyVLA / SmolVLA"],
    blurb: "A mobile robot that follows a technician, localizes tools via RGB-D, navigates the workspace, manipulates with a Franka FR3, and collects LeRobot/HDF5 data for VLA training & evaluation.",
    role: "End-to-end integration · perception · manipulation · data pipeline",
    stack: "ROS2 · Gazebo · Isaac Sim · Nav2 · SLAM · MoveIt · YOLO-Pose + Kalman · TinyVLA · SmolVLA · LeRobot",
    highlights: [
      "Human detection & tracking (YOLO-Pose + Kalman)",
      "RGB-D tool localization & pick-place",
      "Closed-loop VLA rollout evaluation",
      "Automated episode collection pipelines",
    ],
    kind: "mobile-manip",
    videos: [
      { src: "assets/videos/m2_smolvla_isaacsim.mp4", label: "SmolVLA in Isaac Sim — autonomous screwdriver pick-and-place from vision" },
      { src: "assets/videos/m2_navigation_gazebo.mp4", label: "Navigation stack — move-to-goal in Gazebo (4×)" },
    ],
    report: { src: "assets/reports/M2_mobile_manipulation.pdf", label: "Project report (PDF)" },
  },
  {
    id: "drone-stack",
    num: "02",
    year: "2025–26",
    title: "Modular Drone Autonomy Stack",
    tags: ["ROS2", "PX4", "MPC", "RGB-D", "Safe Corridors"],
    blurb: "A modular autonomous drone architecture: state estimation, trajectory MPC, local RGB-D mapping, safe-corridor planning, disturbance observer, allocator, PX4 bridges, benchmarking.",
    role: "Systems architecture · planning/control interfaces · evaluation",
    stack: "ROS2 · PX4 · Trajectory MPC / MPCC · Safe-Corridor Planner · RGB-D Mapper · Horizon Provider · Allocator",
    highlights: [
      "Local env. representation from RGB-D",
      "Constraint-based motion safety",
      "Clean perception → planning → control seams",
      "Benchmark tooling for rollout replay",
    ],
    kind: "drone",
  },
  {
    id: "clf-cbf-qp",
    num: "03",
    year: "2025",
    title: "Robust CLF-CBF-QP Drone Control",
    tags: ["Control", "SE(3)", "Optimization", "Gazebo"],
    blurb: "M1 research internship at Laboratoire DRIVE/ISAT. Geometric control on SE(3) combined with Control Lyapunov & Barrier Functions solved as a QP — robust autonomous obstacle avoidance.",
    role: "Theory → ROS/Gazebo implementation · validation",
    stack: "Geometric control SE(3) · CLF · CBF · QP · ROS · Gazebo",
    highlights: [
      "Nominal position RMSE < 6 cm",
      "Controller at 500 Hz — up to 1000 Hz",
      "Obstacle scenarios validated",
      "Safety encoded as convex constraints",
    ],
    kind: "clf",
    report: { src: "assets/reports/M1_drive_clf_cbf.pdf", label: "Internship report (PDF)" },
    report2: { src: "assets/reports/M1_drive_attestation.pdf", label: "Internship attestation (PDF)" },
  },
  {
    id: "pointnet",
    num: "04",
    year: "2024",
    title: "PointNet — 3D Point Cloud Classification",
    tags: ["PyTorch", "3D Deep Learning", "ModelNet40"],
    blurb: "PointMLP, vanilla PointNet, and PointNet with input T-Net compared on ModelNet40. Explored permutation invariance, symmetric pooling, augmentations.",
    role: "Training experiments · ablations · analysis",
    stack: "PyTorch · ModelNet40 · T-Net · jitter/shift/scale/dropout augs",
    highlights: [
      "≈ 90% accuracy (tuned)",
      "T-Net: alignment robustness",
      "Shared MLP + symmetric pooling",
      "Careful augmentation study",
    ],
    kind: "pointnet",
    report: { src: "assets/reports/PointNet_3DML.pdf", label: "3D ML report (PDF)" },
  },
  {
    id: "ur3e",
    num: "05",
    year: "2025",
    title: "UR3e Pick-and-Place — ROS2 + MoveIt",
    tags: ["UR3e", "MoveIt", "Polyscope", "Contact Sensing"],
    blurb: "Industrial arm programming: Polyscope pick-and-place, contact sensing, ROS2 + UR driver + MoveIt trajectory planning. Work-frame / TCP understanding in practice.",
    role: "Lab project — manipulator integration",
    stack: "UR3e · Polyscope · ROS2 · UR driver · MoveIt",
    highlights: ["Work-frame / TCP setup", "Contact-aware programs", "MoveIt trajectories on real hardware"],
    kind: "ur3e",
    report: { src: "assets/reports/UR3e_ROS2.pdf", label: "Lab report (PDF)" },
  },
  {
    id: "spherical",
    num: "06",
    year: "2024",
    title: "Spherical Robot — CAD to ROS2/Gazebo",
    tags: ["Onshape", "URDF/SDF", "ROS2", "Reaction Wheels"],
    blurb: "RT-G inspired spherical robot: outer rolling shell, level inner frame, four reaction wheels, IMU, stereo pair. Full CAD → URDF → Gazebo workflow.",
    role: "Mechanism design · simulation bringup",
    stack: "Onshape · URDF/SDF · ROS2 control · Gazebo · IMU · stereo RGB",
    highlights: ["Nonstandard locomotion", "CAD-to-sim pipeline", "Attitude-control concepts"],
    kind: "sphere",
    videos: [
      { src: "assets/videos/spherical_bot.mp4", label: "Spherical robot in Gazebo" },
    ],
  },
  {
    id: "maze",
    num: "07",
    year: "2023",
    title: "Maze Solver — Webots + Real Robot",
    tags: ["Visual Servoing", "DFS", "OpenCV", "Embedded"],
    blurb: "Unknown-maze explorer. Two-pass: DFS until goal, then direct replay of simplified shortest path. Binary thresholding + image moments + PID steering.",
    role: "Sim-first, then hardware — competition build",
    stack: "Webots · OpenCV thresholding · moments/centroid · PID · turn encoding L/F/R/B",
    highlights: ["DFS exploration", "Path simplification on backtrack", "Visual line following"],
    kind: "maze",
  },
  {
    id: "africa-cup",
    num: "08",
    year: "2022–23",
    title: "League of Robotics Africa — Competition",
    tags: ["Raspberry Pi", "OpenCV", "PID", "Teamwork"],
    blurb: "Team of 5. Two robots: (1) teleop miniature mobile manipulator for 1v1, (2) autonomous loading/unloading robot with visual-servoing line following on Pi 4 + HD camera.",
    role: "Robotics maker · embedded · vision",
    stack: "Raspberry Pi 4 · HD Camera · OpenCV · PID steering",
    highlights: ["Two distinct robots shipped", "Line-following via moments", "Competition-grade build"],
    kind: "africa",
  },
];

export const EXPERIENCE = [
  {
    date: "Mar → Sep 2026",
    title: "Research Internship — VLA for Robotic Exploration",
    org: "Institut Pascal · UCA · Aubière",
    points: [
      "Vision-Language-Action models guiding exploration toward unseen static objects",
      "Language-defined goals without direct target image",
      "Adaptation / fine-tuning of VLA systems, multimodal fusion",
      "Contact-based exploration, short-range sensing",
    ],
  },
  {
    date: "Apr → Sep 2025",
    title: "M1 Research Internship — Drone Control & Obstacle Avoidance",
    org: "Laboratoire DRIVE / ISAT · UB Europe · Nevers",
    points: [
      "Robust CLF-CBF-QP for autonomous drone navigation",
      "Geometric control on SE(3), optimization-based safety constraints",
      "ROS / Gazebo implementation, RMSE < 6 cm, 500–1000 Hz loops",
    ],
  },
  {
    date: "2024",
    title: "Industrial Internship — LD Azouaou",
    org: "Agricultural / lifting machinery · Algeria",
    points: ["Fabrication, assembly, machining", "Reverse engineering & SolidWorks", "Production exposure"],
  },
  {
    date: "2023",
    title: "Industrial Internship — SPA Somedial",
    org: "Pharmaceutical production · Algeria",
    points: ["Maintenance & utilities", "Automated production lines", "Real-industry system exposure"],
  },
];

export const EDUCATION = [
  { date: "2025–26", title: "M2 Robotics & Artificial Perception", org: "Université Clermont Auvergne", note: "S1: 15.60/20 · Rank 1/16" },
  { date: "2024–25", title: "M1 Automation & Robotics", org: "Université Clermont Auvergne", note: "15.16/20 · Rank 3/42" },
  { date: "2020–24", title: "Engineering Degree — Mechatronics (BAC+4)", org: "ENSTA Algeria", note: "Valedictorian 1/17 · Avg 14.69/20" },
];

export const SKILL_GROUPS = [
  {
    title: "Robotics Middleware & Simulation",
    items: ["ROS2", "Gazebo", "Isaac Sim", "Nav2", "MoveIt", "TF2", "URDF/Xacro", "PX4"],
  },
  {
    title: "Perception & AI",
    items: ["PyTorch", "OpenCV", "YOLO", "PointNet", "TinyVLA / SmolVLA", "RGB-D", "Multimodal fusion", "3D vision"],
  },
  {
    title: "Control · Estimation · Optimization",
    items: ["CLF-CBF-QP", "MPC / MPCC", "PID", "Kalman", "Geometric ctrl SE(3)", "Trajectory tracking", "Safe corridors"],
  },
  {
    title: "Programming & Tools",
    items: ["Python", "C++", "Linux", "Git", "Docker", "HDF5 / LeRobot"],
  },
  {
    title: "CAD · Mechanical",
    items: ["SolidWorks", "Onshape", "Reverse engineering", "3D printing"],
  },
  {
    title: "Languages",
    items: ["French · C2", "English · C2"],
  },
];
